app = "cashflow-check-c7ec35c"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  context = ".."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 25
    hard_limit = 50
