# Digital Ocean App Platform Configuration
# This file defines the services and deployment configuration
#
# NOTE: This file is for reference only. To apply changes, use:
#   doctl apps update <app-id> --spec .do/app.yaml

name: cashflow-scheduler
region: sfo
features:
- buildpack-stack=ubuntu-22

# API Service - FastAPI Backend
services:
  - name: cashflow-scheduler
    # Use Dockerfile for Python FastAPI app
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: SpacePlushy/cashflow-scheduler
      branch: main
      deploy_on_push: true

    # Environment configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

    # HTTP configuration
    http_port: 8000

    # Environment variables
    envs:
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: "8000"

  # Web Service - Next.js Frontend
  - name: cashflow-scheduler2
    # Use Dockerfile for Next.js app
    # NOTE: dockerfile_path is relative to repo root, not source_dir
    dockerfile_path: web/Dockerfile
    source_dir: /web
    github:
      repo: SpacePlushy/cashflow-scheduler
      branch: main
      deploy_on_push: true

    # Environment configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    # HTTP configuration
    http_port: 3000

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production

# Configure ingress routing
ingress:
  rules:
    # Root path goes to web (frontend)
    - component:
        name: cashflow-scheduler2
      match:
        path:
          prefix: /
    # /api path goes to API service
    - component:
        name: cashflow-scheduler
      match:
        path:
          prefix: /api
