# Digital Ocean App Platform Configuration
# This file defines the services and deployment configuration

name: cashflow-scheduler

# API Service - FastAPI Backend
services:
  - name: api
    # Use Dockerfile for Python FastAPI app
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/cashflow-scheduler
      branch: main
      deploy_on_push: true

    # Environment configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - upgrade to basic-xs ($12/month) for better performance

    # HTTP configuration
    http_port: 8000

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: "8000"
      - key: CORS_ORIGINS
        value: ${web.PUBLIC_URL}

    # Routes (accessible at api.your-app.ondigitalocean.app)
    routes:
      - path: /

  # Web Service - Next.js Frontend
  - name: web
    # Next.js build configuration
    build_command: cd web && npm ci && npm run build
    run_command: cd web && npm start
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/cashflow-scheduler
      branch: main
      deploy_on_push: true

    # Environment configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month

    # HTTP configuration
    http_port: 3000

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${api.PUBLIC_URL}  # Auto-references API service URL

    # Routes (accessible at your-app.ondigitalocean.app)
    routes:
      - path: /

# Optional: Database (if you add one later)
# databases:
#   - name: postgres
#     engine: PG
#     version: "14"
#     size: db-s-1vcpu-1gb

# Domains (configure custom domains here)
# domains:
#   - domain: your-custom-domain.com
#     type: PRIMARY
#   - domain: www.your-custom-domain.com
#     type: ALIAS
