name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check cashflow
          black --check cashflow

      - name: Type check
        run: |
          mypy cashflow

      - name: Tests
        run: |
          pytest -q --maxfail=1

